//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchetishee
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prodajiEntities : DbContext
    {
        public prodajiEntities()
            : base("name=prodajiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ed_izm> ed_izm { get; set; }
        public virtual DbSet<kategor> kategor { get; set; }
        public virtual DbSet<klient> klient { get; set; }
        public virtual DbSet<manager> manager { get; set; }
        public virtual DbSet<seriya> seriya { get; set; }
        public virtual DbSet<sklad> sklad { get; set; }
        public virtual DbSet<spos_opl> spos_opl { get; set; }
        public virtual DbSet<status_klient> status_klient { get; set; }
        public virtual DbSet<status_zakaz> status_zakaz { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tovar> tovar { get; set; }
        public virtual DbSet<UZ_admin> UZ_admin { get; set; }
        public virtual DbSet<UZ_director> UZ_director { get; set; }
        public virtual DbSet<UZ_manager> UZ_manager { get; set; }
        public virtual DbSet<valuta> valuta { get; set; }
        public virtual DbSet<vid_tov> vid_tov { get; set; }
        public virtual DbSet<zakaz> zakaz { get; set; }
        public virtual DbSet<detali_zakaza> detali_zakaza { get; set; }
    }
}
