//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchetishee
{
    using System;
    using System.Collections.Generic;
    
    public partial class detali_zakaza
    {
        public int id_zakaz { get; set; }
        public int id_tovara { get; set; }
        public int kolichestvo { get; set; }
    
        public virtual tovar tovar { get; set; }
        public virtual zakaz zakaz { get; set; }
    }
}
