//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchetishee
{
    using System;
    using System.Collections.Generic;
    
    public partial class klient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public klient()
        {
            this.zakaz = new HashSet<zakaz>();
        }
    
        public int id_kli { get; set; }
        public int id_status_kli { get; set; }
        public string familiya_kli { get; set; }
        public string imya_kli { get; set; }
        public string otchestvo { get; set; }
        public string Naim_Company { get; set; }
        public string nomer_tel_kli { get; set; }
        public string email_kli { get; set; }
        public string inn_kli { get; set; }
    
        public virtual status_klient status_klient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zakaz> zakaz { get; set; }
    }
}
