//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchetishee
{
    using System;
    using System.Collections.Generic;
    
    public partial class tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tovar()
        {
            this.detali_zakaza = new HashSet<detali_zakaza>();
        }
    
        public int id_tovar { get; set; }
        public string artikul { get; set; }
        public int id_kategor { get; set; }
        public int id_vid_tov { get; set; }
        public int id_serii { get; set; }
        public string nomenklatur { get; set; }
        public Nullable<double> stoimost { get; set; }
        public int id_valuta { get; set; }
        public int id_sklad { get; set; }
        public Nullable<int> kolichestvo { get; set; }
        public int id_ed_izm { get; set; }
    
        public virtual ed_izm ed_izm { get; set; }
        public virtual kategor kategor { get; set; }
        public virtual seriya seriya { get; set; }
        public virtual sklad sklad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detali_zakaza> detali_zakaza { get; set; }
        public virtual valuta valuta { get; set; }
        public virtual vid_tov vid_tov { get; set; }
    }
}
