//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchetishee
{
    using System;
    using System.Collections.Generic;
    
    public partial class UZ_admin
    {
        public int id_uz_admin { get; set; }
        public string login_admin { get; set; }
        public string password_admin { get; set; }
    }
}
