//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchetishee
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zakaz()
        {
            this.detali_zakaza = new HashSet<detali_zakaza>();
        }
    
        public int id_zakaz { get; set; }
        public int id_kli { get; set; }
        public int id_status_zakaz { get; set; }
        public int id_spos_opl { get; set; }
        public int id_valuta { get; set; }
        public int id_manager { get; set; }
        public Nullable<System.DateTime> data_zakaza { get; set; }
    
        public virtual klient klient { get; set; }
        public virtual manager manager { get; set; }
        public virtual spos_opl spos_opl { get; set; }
        public virtual status_zakaz status_zakaz { get; set; }
        public virtual valuta valuta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detali_zakaza> detali_zakaza { get; set; }
    }
}
